@IsTest
public class Test_ReminderForExpenseRecApproval {
    
  
   /* DA_Expenso_App__Expense__c record = new DA_Expenso_App__Expense__c();
    
    record.CreatedById= 'EXP-0001';
    record.DA_Expenso_App__Amount__c=1234;
    record.DA_Expenso_App__AP_Invoice_Number__c='Invoice';
    record.DA_Expenso_App__Chargeback_to_Customer__c='false';
    record.DA_Expenso_App__Client__c='0015A000027iCkCQAU';
   // record.DA_Expenso_App__Date__c=Date.today();
    record.DA_Expenso_App__Department__c='Dept';
    record.DA_Expenso_App__Description__c='desc';
    record.DA_Expenso_App__Expense_Type__c='Hotel';
    record.DA_Expenso_App__isDeleted__c='false';  
    record.DA_Expenso_App__IsSubmitted__c='false';
    record.DA_Expenso_App__Location__c='Delhi';
    record.DA_Expenso_App__Manager_For_Approval__c='Manager';
    record.DA_Expenso_App__Related_Opportunity__c='Burlington Textiles Weaving Plant Generator';
    record.DA_Expenso_App__SalesTax__c='34567';
    record.DA_Expenso_App__Status__c='Pending';
    record.DA_Expenso_App__Vendor__c='Bond';
    
    insert record; */

}